version: '3.5'
services:
  app:
    build: .
    ports:
      - "8070:8070" # frotnend
      - "8080:8080" #authend
      - "8090:8090" # backend
    env_file:
      - .env
    networks:
      - milvus


networks:
  milvus:
    external: true
