version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - milvus

volumes:
  sqldb:

networks:
  milvus:
    external: true
