version: '3.5'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - milvus

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - milvus

volumes:
  sqldb:

networks:
  milvus:
    external: true
