version: '3'

services:
  tooljet:
    tty: true
    container_name: tooljetservice
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    #restart: always
    env_file: .env
    ports:
      - 8005:85
    environment:
      SERVE_CLIENT: "true"
      PORT: "85"
    command: npm run start:prod
    networks:
      - milvus

networks:
  milvus:
    external: true
