version: '3.5'
services:
  app:
    build: .
    ports:
      - "8070:8070" # frotnend
      - "8080:8080" #authend
      - "8090:8090" # backend
    env_file:
      - .env
    networks:
      - milvus

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - milvus
    # command: -p 5433 # iam unable to run authend on 5433


volumes:
  sqldb:

networks:
  milvus:
    external: true
