"""Add new columns to querydb table

Revision ID: 08a57568766a
Revises: 
Create Date: 2023-07-15 03:24:59.701386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08a57568766a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promptdb')
    op.drop_table('app_configs')
    op.drop_table('prompt_templates')
    op.drop_table('completion_activity_log')
    op.add_column('querydb', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('querydb', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('querydb', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('querydb', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('querydb', 'total_cost')
    op.drop_column('querydb', 'completion_tokens')
    op.drop_column('querydb', 'prompt_tokens')
    op.drop_column('querydb', 'total_tokens')
    op.create_table('completion_activity_log',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('corelation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('completion_cost_usd', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('completion_method', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name='completion_activity_log_pkey')
    )
    op.create_table('prompt_templates',
    sa.Column('template_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('template_id', name='prompt_templates_pkey')
    )
    op.create_table('app_configs',
    sa.Column('config_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('config_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('config_key', name='app_configs_pkey')
    )
    op.create_table('promptdb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='promptdb_pkey')
    )
    # ### end Alembic commands ###
